/**
 * Section catalogue — the single source of the navigation order, per-section
 * summaries and the feature descriptions surfaced as hover tooltips.
 *
 * Every section declares its features here so the landing page can show a
 * general summary and each section header can explain its own workings
 * through small hovers (chips with tooltips).
 */

export const SECTIONS = [
  {
    id: "overview",
    code: "OPS",
    label: "Overview",
    color: "var(--accent)",
    title: "Executive Overview",
    summary:
      "Cross-engine roll-up of the latest persisted results: overall network " +
      "status, critical incidents, likely root causes and recommended next " +
      "actions. Everything on this page is read from artefacts already on " +
      "disk — nothing is recomputed or executed.",
    features: [
      {
        name: "Network status",
        tip: "One traffic-light status derived from correlated incidents, configuration findings and network-health anomalies in the selected runs.",
      },
      {
        name: "Incident roll-up",
        tip: "Counts of total and high/critical incidents from the latest correlation run, with affected devices deduplicated across incidents.",
      },
      {
        name: "Root causes",
        tip: "Root-cause hypotheses attached by correlation rules (e.g. DOS_SATURATION) to the incidents in focus.",
      },
      {
        name: "Recommended actions",
        tip: "Deduplicated, owner-tagged action list drawn from incident recommendations. Advisory only — the console never executes anything.",
      },
    ],
  },
  {
    id: "live",
    code: "LIVE",
    label: "Live Monitor",
    color: "var(--system)",
    title: "Live Monitoring",
    summary:
      "Current state of the offline streaming demo: active incidents, the " +
      "most recent events from every engine, and event distributions by " +
      "severity, type and source. The stream is a replay of persisted " +
      "artefacts — no packet capture and no device polling.",
    features: [
      {
        name: "Active incidents",
        tip: "Incidents currently open in the replayed stream, with severity, affected device and the time each was emitted.",
      },
      {
        name: "Event feed",
        tip: "Most recent events across engines (cyber alerts, health anomalies, config findings, topology warnings) ordered newest first.",
      },
      {
        name: "Severity mix",
        tip: "Distribution of replayed events by severity. Colors follow the reserved status palette and every bar carries a visible label.",
      },
      {
        name: "Engine mix",
        tip: "Which engine produced the events — Engine A (cyber), Engine B (health), Engine C (configuration), correlation, system.",
      },
    ],
  },
  {
    id: "training",
    code: "TRN",
    label: "Training & Validation",
    color: "var(--engine-a)",
    title: "Training · Testing · Validation",
    summary:
      "Every persisted experiment across datasets and models with its train, " +
      "validation and test metrics, the best run per dataset+model pair, " +
      "dataset validation reports and feature-engineering summaries. Runs " +
      "are launched manually from the command line; this page only reads " +
      "their outputs.",
    features: [
      {
        name: "Experiment explorer",
        tip: "All runs under outputs/experiments, filterable by dataset and model, with seed, device and creation time for reproducibility.",
      },
      {
        name: "Best-run matrix",
        tip: "Highest test-F1 run per dataset+model pair — the comparison used to pick production candidates.",
      },
      {
        name: "Split metrics",
        tip: "Precision, recall, F1, ROC AUC and false-positive rate reported separately for train, validation and test splits — never accuracy alone.",
      },
      {
        name: "Validation reports",
        tip: "Dataset-level validation artefacts and the model validation report generated by the reporting pipeline.",
      },
      {
        name: "Feature reports",
        tip: "Selected/removed feature counts per dataset from the feature-engineering stage.",
      },
    ],
  },
  {
    id: "engine_a",
    code: "ENG-A",
    label: "Engine A · Cyber",
    color: "var(--engine-a)",
    title: "Engine A — Cyber Intrusion Detection",
    summary:
      "Production intrusion-detection models per dataset (NSL-KDD, " +
      "UNSW-NB15, CICIDS2017) from the model registry, with their validated " +
      "test metrics and linked explainability, error-analysis and " +
      "visualization artefacts.",
    features: [
      {
        name: "Production registry",
        tip: "The model promoted to production for each dataset, when it was promoted and why.",
      },
      {
        name: "Detection metrics",
        tip: "Test F1 and ROC AUC for each production model, read from the registered experiment's metrics.",
      },
      {
        name: "Artefact links",
        tip: "Whether explainability (SHAP), error-analysis and visualization outputs exist for the production experiment.",
      },
    ],
  },
  {
    id: "engine_b",
    code: "ENG-B",
    label: "Engine B · Health",
    color: "var(--engine-b)",
    title: "Engine B — Network Health Prediction",
    summary:
      "Latest network-health experiments per telemetry dataset: anomaly " +
      "rates on the test split, model type, and detection metrics where " +
      "labels exist. Trained on SNMP counters and network telemetry.",
    features: [
      {
        name: "Anomaly rate",
        tip: "Share of test samples the model flags as anomalous — the primary degradation signal per dataset.",
      },
      {
        name: "Detection metrics",
        tip: "Precision / recall / F1 / ROC AUC where the dataset is labeled; unlabeled datasets report anomaly counts only.",
      },
      {
        name: "Model lineup",
        tip: "Isolation Forest and autoencoder-family models; each row shows the most recent experiment for its dataset.",
      },
    ],
  },
  {
    id: "engine_c",
    code: "ENG-C",
    label: "Engine C · Config",
    color: "var(--engine-c)",
    title: "Engine C — Network Configuration Intelligence",
    summary:
      "Offline analysis of a network snapshot: device inventory, port/VLAN/" +
      "PoE state, topology, rule findings, device health and the dry-run " +
      "remediation plan. Strictly read-only — plans require explicit human " +
      "confirmation and are never executed from here.",
    features: [
      {
        name: "Snapshot picker",
        tip: "Choose which persisted assessment run (snapshot) to inspect; the latest is selected by default.",
      },
      {
        name: "Inventory",
        tip: "Devices with management IP and platform, plus per-interface status, mode, VLAN, speed/duplex and PoE state.",
      },
      {
        name: "Findings",
        tip: "Rule-engine findings (STP, VLAN, port, security…) with severity, evidence, recommendation and confidence.",
      },
      {
        name: "Topology",
        tip: "LLDP/CDP-derived device graph with per-node risk score and finding count.",
      },
      {
        name: "Remediation plan",
        tip: "Proposed actions with exact commands, rollback and verification steps. Dry-run only; execution requires explicit confirmation outside this console.",
      },
      {
        name: "Device health",
        tip: "Per-device roll-up: interfaces, trunks, PoE ports, STP blocks, findings and highest severity.",
      },
    ],
  },
  {
    id: "correlation",
    code: "COR",
    label: "Correlation",
    color: "var(--correlation)",
    title: "Correlation Engine — Unified Incidents",
    summary:
      "Combines Engine A cyber signals, Engine B health anomalies and " +
      "Engine C configuration findings into unified incidents — e.g. high " +
      "CPU + CRC errors + port scan → possible DDoS overloading a switch. " +
      "Each incident carries evidence, confidence and recommended actions.",
    features: [
      {
        name: "Incident list",
        tip: "Correlated incidents with severity, confidence, triggering rule and the engines that contributed evidence.",
      },
      {
        name: "Signals",
        tip: "The raw per-engine signals that fed the correlation rules for this run.",
      },
      {
        name: "Evidence trail",
        tip: "Per-incident evidence grouped by engine, so every conclusion is explainable back to its source artefacts.",
      },
      {
        name: "Run picker",
        tip: "Inspect any persisted correlation run; the latest is selected by default.",
      },
    ],
  },
  {
    id: "history",
    code: "HIST",
    label: "History",
    color: "var(--muted)",
    title: "History & Past Data",
    summary:
      "Everything the platform has persisted over time: assessment runs " +
      "(Engine C snapshots), incident runs (correlation) and the replayed " +
      "event log. Runs are never overwritten, so past results stay " +
      "reviewable.",
    features: [
      {
        name: "Assessment runs",
        tip: "Every Engine C snapshot with its generation time, newest first, latest marked.",
      },
      {
        name: "Incident runs",
        tip: "Every correlation run with its timestamp — pick any of them in the Correlation section.",
      },
      {
        name: "Event log",
        tip: "Full replayed streaming event history (newest first), including events that have scrolled out of the live view.",
      },
    ],
  },
  {
    id: "safety",
    code: "SAFE",
    label: "Safety",
    color: "var(--status-good)",
    title: "Safety Posture",
    summary:
      "The guarantees this console operates under: read-only, offline, " +
      "artefact-driven. No live device access, no packet capture, no " +
      "command execution — remediation is planned as dry-run and requires " +
      "explicit human confirmation, with every action audit-logged.",
    features: [
      {
        name: "Read-only guarantee",
        tip: "The web console and its API only read persisted files; there is no code path that contacts a device or executes a command.",
      },
      {
        name: "Dry-run audit",
        tip: "Validation results of the latest dry-run: total, validated, blocked and executed (always zero) actions, with the audit-log location.",
      },
      {
        name: "Confirmation model",
        tip: "Destructive actions (shutdown, PoE change, VLAN change) always require explicit human confirmation and ship with rollback and verification commands.",
      },
    ],
  },
];

export function sectionById(id) {
  return SECTIONS.find((s) => s.id === id) ?? SECTIONS[0];
}
