/**
 * Engine A (cyber intrusion detection) and Engine B (network health)
 * sections — production registry and latest health experiments.
 */

import { useApi } from "../api.js";
import { int, metric, pct, ts, titleCase } from "../lib/format.js";
import {
  SectionHeader,
  StatTile,
  EmptyState,
  DataTable,
  InfoHover,
  Loader,
} from "../components/primitives.jsx";

export function EngineA({ section }) {
  const state = useApi("/api/engine-a");
  return (
    <>
      <SectionHeader section={section} />
      <Loader state={state}>
        {(data) =>
          data.available ? <EngineABody data={data} /> : <EmptyState message={data.message} />
        }
      </Loader>
    </>
  );
}

function EngineABody({ data }) {
  return (
    <>
      <div className="grid tiles" style={{ marginBottom: 18 }}>
        <StatTile
          label="Production models"
          value={int(data.productionModelCount)}
          note="one promoted model per dataset"
          tip="Models promoted to production in the registry after validation."
        />
        <StatTile
          label="Validation report"
          value={data.validationReportAvailable ? "available" : "—"}
          note="outputs/reports/model_validation_report.md"
          tip="The cross-model validation report generated by the reporting pipeline."
        />
      </div>
      <div className="card">
        <h3>
          Production registry
          <InfoHover tip="Test F1 comes from the registry's best-per-dataset record; ROC AUC is read from the promoted experiment's metrics. Artefact ticks mark existing explainability / error-analysis / visualization outputs." />
        </h3>
        <DataTable
          columns={[
            { key: "dataset", label: "Dataset", render: (r) => titleCase(r.dataset) },
            { key: "modelType", label: "Model", render: (r) => titleCase(r.modelType) },
            { key: "testF1", label: "Test F1", num: true, render: (r) => metric(r.testF1) },
            { key: "rocAuc", label: "ROC AUC", num: true, render: (r) => metric(r.rocAuc) },
            { key: "promotedAt", label: "Promoted", render: (r) => ts(r.promotedAt) },
            {
              key: "artifacts",
              label: "Artefacts",
              render: (r) =>
                r.artifacts
                  ? ["explainability", "errorAnalysis", "visualizations"]
                      .filter((k) => r.artifacts[k])
                      .map((k) => titleCase(k))
                      .join(" · ") || "—"
                  : "—",
            },
            {
              key: "experimentId",
              label: "Experiment",
              render: (r) => <span className="mono">{r.experimentId}</span>,
            },
          ]}
          rows={data.models}
        />
      </div>
    </>
  );
}

export function EngineB({ section }) {
  const state = useApi("/api/engine-b");
  return (
    <>
      <SectionHeader section={section} />
      <Loader state={state}>
        {(data) =>
          data.available ? <EngineBBody data={data} /> : <EmptyState message={data.message} />
        }
      </Loader>
    </>
  );
}

function EngineBBody({ data }) {
  return (
    <>
      <div className="grid tiles" style={{ marginBottom: 18 }}>
        <StatTile
          label="Telemetry datasets"
          value={int(data.datasets.length)}
          note="latest experiment per dataset"
          tip="Each row of the table is the most recent network-health experiment for its dataset."
        />
        <StatTile
          label="Anomaly headline"
          value={data.anomalyStatus ? data.anomalyStatus.split(":")[1]?.trim() : "—"}
          note={data.anomalyStatus?.split(":")[0]}
          tip="The dataset with the highest predicted anomaly rate on its test split."
        />
      </div>
      <div className="card">
        <h3>
          Latest experiments
          <InfoHover tip="Anomaly rate = predicted anomalous samples / test samples. Precision/recall/F1/ROC AUC appear only for labeled datasets." />
        </h3>
        <DataTable
          columns={[
            { key: "dataset", label: "Dataset", render: (r) => titleCase(r.dataset) },
            { key: "modelName", label: "Model", render: (r) => titleCase(r.modelName) },
            {
              key: "anomalyRate",
              label: "Anomaly rate",
              num: true,
              render: (r) => pct(r.anomalyRate),
            },
            {
              key: "nAnomalousPredicted",
              label: "Anomalous / samples",
              num: true,
              render: (r) => `${int(r.nAnomalousPredicted)} / ${int(r.nSamples)}`,
            },
            { key: "precision", label: "Precision", num: true, render: (r) => metric(r.precision) },
            { key: "recall", label: "Recall", num: true, render: (r) => metric(r.recall) },
            { key: "f1", label: "F1", num: true, render: (r) => metric(r.f1) },
            { key: "rocAuc", label: "ROC AUC", num: true, render: (r) => metric(r.rocAuc) },
            {
              key: "labeled",
              label: "Labeled",
              render: (r) => (r.labeled ? "yes" : "no"),
            },
          ]}
          rows={data.datasets}
        />
      </div>
    </>
  );
}
